export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_ALL_EVENTS_SUCCESS = 'FETCH_ALL_EVENTS_SUCCESS';
export const FETCH_ALL_EVENTS_FAIL = 'FETCH_ALL_EVENTS_FAIL';
export const FETCH_ALL_EVENTS_START = 'FETCH_ALL_EVENTS_START';

export const FETCH_ADMIN_EVENTS_SUCCESS = 'FETCH_ADMIN_EVENTS_SUCCESS';
export const FETCH_ADMIN_EVENTS_FAIL = 'FETCH_ADMIN_EVENTS_FAIL';
export const FETCH_ADMIN_EVENTS_START = 'FETCH_ADMIN_EVENTS_START';